#pragma config(Motor,  motor1,          Right,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          Middle,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          Left,          tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	While(true)
	{
		if(abs(vexRT[ChA])>15 || abs(vexRT[ChB]>15 || abs(vexRT[ChD])>15)
		{
			if(abs(vexRT[ChA])>15 && abs(vexRT[ChB]<15 && abs(vexRT[ChD])<15)
			{
				motor[Middle]=vexRT[ChA];
			}
			else
			{
				if(abs(vexRT[ChA])<15 && abs(vexRT[ChB]>15 && abs(vexRT[Ch4])<15)
				{
					motor[Right]=vexRT[ChB];
					motor[Left]=vexRT[ChB];
				}
				else
				{
					if(abs(vexRT[ChA])<15 && abs(vexRT[ChB]<15 && abs(vexRT[Ch4])>15)
					{
						motor[Right]=-vexRT[ChD];
						motor[Left]=vexRT[ChD];
					}
					else
					{
						if(abs(vexRT[ChA])>15 && abs(vexRT[ChB]>15 && abs(vexRT[Ch4])>15)
						{
							motor[Right]=vexRT[ChB]-vexRT[ChD];
							motor[Left]=vexRT[ChB]+vexRT[ChD];
							motor[Middle]=vexRT[ChA];
						}
					}
				}
			}
		}
	}

}
