#pragma config(Motor,	 port2,						North,				 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port3,						East,					 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port4,						South,				 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port5,						West,					 tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

#define LeftX Ch4
#define LeftY Ch3
#define RightX Ch1
#define RightY Ch2

task main()
{
	while(true)
	{
		//Moving base forward/backward/side2side

		//sensing input from right analog control stick and left analog stick and powering motors
		if(abs(vexRT[LeftY]) > 15 || abs(vexRT[RightY]) > 15 || abs(vexRT[LeftX]) > 15)
		{
			//Pushing up or down on right analog control stick and powering East and West motors
			if (abs(vexRT[RightX]) < 15 && abs(vexRT[RightY]) > 15 && abs(vexRT[LeftX]) < 15)
			{
				motor[East] = vexRT[RightY];
				motor[West] = vexRT[RightY];
			}
			else if (abs(vexRT[RightX]) > 15 && abs(vexRT[RightY]) < 15 && abs(vexRT[LeftX]) < 15)
			{
				motor[North] = vexRT[RightX];
				motor[South] = vexRT[RightX];
			}
			else if (abs(vexRT[RightX]) < 15 && abs(vexRT[RightY]) < 15 && abs(vexRT[LeftX]) > 15)
			{
				motor[West] = vexRT[LeftX];
				motor[East] = -vexRT[LeftX];
			}
			else if (abs(vexRT[RightX]) > 15 && abs(vexRT[RightY]) > 15 && abs(vexRT[LeftX]) > 15)
			{
				motor[North] = vexRT[RightX]/2;
				motor[South] = vexRT[RightX]/2;
				motor[West] = (vexRT[RightY]/2)+vexRT[LeftX]/2;
				motor[East] = (vexRT[RightY]/2)-vexRT[LeftX]/2;
			}
		}
	}
}
