#pragma config(Motor,  port1,           North,         tmotorVex393, openLoop)
#pragma config(Motor,  port2,           East,          tmotorVex393, openLoop)
#pragma config(Motor,  port3,           South,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           West,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LeftX Ch4
#define LeftY Ch3
#define RightX Ch1
#define RightY Ch2

task main()
{
	while(true)
	{
			//Moving base forward/backward/side2side

		//sensing input from right analog control stick and left analog stick and powering motors
		if(abs(vexRT[ChA])>15 || abs(vexRT[ChB])>15 || abs(vexRT[ChD])>15)
		{
			//Pushing up or down on right analog control stick and powering East and West motors
			if (abs(vexRT[ChA])<15 && abs(vexRT[ChB])>15 && abs(vexRT[ChD])<15)
			{
				motor[East]=vexRT[ChB];
				motor[West]=vexRT[ChB];
			}
			else
				//Pushing left or right on right analog control stick and powering North and South motors
			{if (abs(vexRT[ChA])>15 && abs(vexRT[ChB])<15 && abs(vexRT[ChD])<15)
				{
					motor[North]=vexRT[ChA];
					motor[South]=vexRT[ChA];
				}
				else
					//Pushing left or right on the left analog control stick and powering North and -South motors
					{if (abs(vexRT[ChA])<15 && abs(vexRT[ChB])<15 && abs(vexRT[ChD])>15)
						{
						motor[West]=vexRT[ChD];
						motor[East]=-vexRT[ChD];
						}
					else
						//Turning and Moving
						{if (abs(vexRT[ChA])>15 && abs(vexRT[ChB])>15 && abs(vexRT[ChD])>15)
							{
								motor[North]=vexRT[ChA]/2;
								motor[South]=vexRT[ChA]/2;
								motor[West]=(vexRT[ChB]/2)+vexRT[ChD]/2;
								motor[East]=(vexRT[ChB]/2)-vexRT[ChD]/2;
							}
						}
					}

		}
	}
}
}
