#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           arm,           tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           fifthWheel,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LeftX Ch4
#define LeftY Ch3
#define RightX Ch1
#define RightY Ch2
#define ButtonL Btn5U
#define ButtonR Btn6U

int getRightX();
int getRightY();
int getLeftX();
int getLeftY();
void setMotors(int leftPower, int rightPower, int midPower);
void setLeftMotor(int power);
void setRightMotor(int power);
void setMidMotor(int power);
bool goForwards();
bool goBackwards();
bool stop();

int timeList[] =
{
  1000,
  3000
};

const int taskNum = sizeof(timeList) / sizeof(timeList[0]);
const int FORWARDS = 1;
const int BACKWARDS = 2;
const int STOP = 3;

int taskList[] =
{
  FORWARDS,
  STOP
};

bool waitList[] =
{
  false,
  false
};

bool doneList[taskNum];

task main()
{
  clearTimer(T1);
  while(true)
  {
    if(vexRT[ButtonL] == 1) {
  	  motor[arm] = 127;
  	}
  	else if (vexRT[ButtonR] == 1) {
  	  motor[arm] = -127;
  	}
  	else {
  	  motor[arm] = 0;
  	}
    setMotors(getLeftY() + getRightX(), getLeftY() - getRightX(), getLeftX());
    //Autonomous V
    for (int i = 0; i < taskNum; i++)
    {
      if (timeList[i] <= time1[T1] && !doneList[i] && (i == 0 || (!waitList[i] || doneList[i - 1])))
      {
        switch(taskList[i])
        {
        	case FORWARDS:
        		doneList[i] = goForwards();
        	case BACKWARDS:
        		doneList[i] = goBackwards();
          case STOP:
            doneList[i] = stop();
          // other tasks
        }
      }
    }
  }
}

// Task #1
bool goForwards()
{
  setMotors(127, 127, 0);
  return true;
}

// Task #2
bool goBackwards()
{
  setMotors(-127, -127, 0);
  return true;
}

// Task #3
bool stop()
{
  setMotors(0, 0, 0);
  return true;
}

int getRightX()
{
  return vexRT[RightX];
}

int getRightY()
{
  return vexRT[RightY];
}

int getLeftX()
{
  return vexRT[LeftX];
}

int getLeftY()
{
  return vexRT[LeftY];
}

void setMotors(int leftPower, int rightPower, int midPower)
{
  setLeftMotor(leftPower);
  setRightMotor(rightPower);
  setMidMotor(midPower);
}

void setRightMotor(int power)
{
  if (power > 127)
    power = 127;
  if (power < -127)
    power = -127;
  motor[rightMotor] = power;
}

void setLeftMotor(int power)
{
  if (power > 127)
    power = 127;
  if (power < -127)
    power = -127;
  motor[leftMotor] = power;
}

void setMidMotor(int power)
{
  if (power > 127)
    power = 127;
  if (power < -127)
    power = -127;
  motor[fifthWheel] = power;
}
